### ISSUE TITLE
extending from Faceter::Mapper

### ISSUE THREAD

**Issue by martinciu** [nepalez/faceter#2]
@nepalez what's correct way of extending `Faceter::Mapper`

I want to add one command `structure` do mapper. When I do this (see below) other commands like `symbolize_keys` are not available.

``` ruby
class ApiMapper::Mapper < Faceter::Mapper
  configure do
    command :structure, ApiMapper::Structure, &ApiMapper::Coerces[:structure]
  end
end
```

**Comment by nepalez** [comment]
@martinciu Actually I didn't plan to extend mappers, so I need to think. This is not the bug, but definitely this feature of extendability could be useful. I think this worth an issue to the `abstract_mapper`

The problem with [configure](https://github.com/nepalez/abstract_mapper/blob/master/lib/abstract_mapper/dsl.rb#L33-L36) is that his method of `AbstractMapper::DSL` redefines all mapper settings. When you call it in your `ApiMapper` the only mapper command is `:structure`.

**Comment by martinciu** [comment]
@nepalez agree that it's not a bug.

I was also thinking of extending `faceter` (or `abstract_mapper`) in this way:

```ruby
class Mapper < Faceter::Mapper
  symbolize_keys

  child_mappings # mappings defined in IssueMapper

  wrap to: :attributes, only: attributes_list
  create from: [:attributes] do |attributes|
    entity_class.new(attributes)
  end
end

class IssueMapper < Mapper
  entity_class Issue
  attributes_list :id, :title, :status
  
  # child_mappings
  rename :statusCode, to: :status
end
```

Does it make any sense to you? Or maybe it's our of the scope of faceter? I'm open for suggestions to solve it in other way. Thanks!

**Comment by nepalez** [comment]
I think it does. But I'd like to play with the idea for some time.

**Comment by nepalez** [comment]
@martinciu Eventually (in `v0.1.0`) I've made mapper's `configure` to update existing set of commands and rules like in your first post in this thread. Would be nice if you could check it and give a feedback :)

The second thing with lazy definition proves to be more tricky. I need to dig it more.
